### ISSUE TITLE
ngCropper call methods, code example needed

### ISSUE THREAD

**Issue by jrbecart** [koorgoo/ngCropper#16]
Like in the cropper website example, how can I do for example:
$().cropper("getCroppedCanvas", { width: 160, height: 90 })
with ngCropper?

**Comment by koorgoo** [comment]
Hi. You can use proxing, see demo.js for example.

**Comment by jrbecart** [comment]
I don't understand how to use the proxy:

$scope.cropperProxy = 'cropper.getCroppedCanvas';
And after...? Sorry if it's a dumb question.

**Comment by koorgoo** [comment]
Ok.
First you should define a proxy name in `$scope`.
```js
$scope.cropper = {}; // This is a container object.
$scope.cropperProxy = 'cropper.first'; // This means that your proxy will be set to $scope.cropper.first
```
Then you should pass `$scope.cropperProxy` to directive via attribute in html.
```html
<img ng-cropper ng-cropper-proxy="cropperProxy" ...>
```
The directive will set cropper function to `$scope.cropper.first` - `$scope.cropper.first()` equals `element.cropper()`. 
Finally `$scope.cropper.first('getCroppedCanvas', { width: 160, height: 90 })` is what you need.

**Comment by koorgoo** [comment]
Working with DOM in controller is a bad practice. Anyway in some cases we must do it.
I agree that proxing is really a bit tricky :smiley:

**Comment by jrbecart** [comment]
Thanks!
