### ISSUE TITLE
Mobile Compatible?

### ISSUE THREAD

**Issue by robinprashanth** [koorgoo/ngCropper#2]
Hi,
I need to integrate this in my android project.so wanted to know is this compatible on the android devices

**Comment by ghengeveld** [comment]
Since this is just a wrapper I think it's safe to say it works if this one does: http://fengyuanchen.github.io/cropper/

It works fine on my Android 4.4.3 phone.

**Comment by koorgoo** [comment]
@robinprashanth
@ghengeveld is absolutely right. ngCropper uses styles of the original cropper so compatibility depends on the latter.
