### ISSUE TITLE
Options undefined in directive

### ISSUE THREAD

**Issue by CristianMR** [koorgoo/ngCropper#5]
Hey guys, I'm testing this library and I found a problem. 

In the directive, there is a preprocess function, with a $q.all than returns lastUpdatedOptions when is resolved. 

```javascript

$q.all(toResolve).then(function(values) {
      var lastUpdatedOptions = values[values.length-1];
      defer.resolve(lastUpdatedOptions);
    });

```

But in my proyect when returns the options, return undefined value because values.length is undefined. To solve this problem, I changed that line to this another 
```javascript
var lastUpdatedOptions = values[_.size(values)-1];
```
because I'm using lodash and I can know the size of the array with that method. I don't know if someone have a similar problem.

Sorry for my english. Thanks

**Comment by koorgoo** [comment]
I refactored promises code. No such issue should appear any more.
