### ISSUE TITLE
Show Preview Doesn't Show Anything

### ISSUE THREAD

**Issue by coommark** [koorgoo/ngCropper#6]
My understanding is that clicking the Show Preview button is supposed to show the cropped image right? But it doesn't work with the exact code in the demo. 

Is there hope we can get help from the contributors here? The parent Cropper is thriving while this here we can't get a working demo.

**Comment by sebastialonso** [comment]
@koorgoo any pointers?

**Comment by koorgoo** [comment]
@coommark try to run
```
make prep  # Install dependencies into bower_components
make demo  # (on Mac) or just open demo/index.html in your browser
```
