### ISSUE TITLE
Conflict with new ngOptions in Angular 1.4

### ISSUE THREAD

**Issue by demetriusnunes** [koorgoo/ngCropper#9]
Hi there,

After we updated to Angular 1.4, ngCropper stopped working due to a conflict with the new ngOptions in Angular 1.4.

A simple change to the directive scope definition to `{ scope: { options: '=ngCropperOptions' } }` fixed the problem.

Would you fix that and release a Angular 1.4 compatible version? Thanks, awesome lib.

**Comment by koorgoo** [comment]
Due to some legacy code I still use 1.26 in production.
Will change to support both angular versions soon.
Thanks for reply @demetriusnunes

**Comment by Lusicrous** [comment]
I've also had some issues with making the options have any effect on the cropper. 

The only options that seem to work right now for me are 'maximize' and 'aspectRatio'. Even in the demo, if I add more options they have no effect whatsoever. In our work project we are using Angular 1.3 and I see that the demo project is using Angular 1.2 and in both cases the options do not work.

**Comment by koorgoo** [comment]
Fixed in https://github.com/koorgoo/ngCropper/commit/ff41008e5260ecd6245c2920a79e7073185b09bc.
